baseURL = "https://kk70.top"
languageCode = "zh-CN"
title = "kk70 的博客"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

disqusShortname = "kk70"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "kk70"

[params]
  author = "kk70"
  subtitle = "专注于Java、服务端、分布式集群、软件架构"
  keywords = "Java,JavaEE,Spring,SpringBoot,PostgreSQL,MySQL,分布式集群"
  description = "专注于Java、服务端、分布式集群、软件架构"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索
  beian = "渝ICP备20009935号"

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "kk70 的博客"
  name = "kk70 的博客"
  url = "https://kk70.top/"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4